function [allaccuracies, allconfidences, allbiasindices] = GetSummaryBehaviourMeasures_Exp6(data)

allaccuracies  = nan(81,16);
allconfidences = nan(81,16);
allbiasindices = nan(81,16);

% run analyses for the original task
for iSub = 61:81
    indsub   = data.subject == iSub;
    
    % define important variables
    perceptualvals  = data.pvs(indsub,:);
    meanofstim      = nanmean(perceptualvals,2);
    catofstim       = meanofstim>0;
    setsize         = sum(~isnan(perceptualvals),2);
    
    % contrast of stimuli
    contrast        = data.contrast(indsub);
    allcontrasts    = unique(contrast);
    lowcontrast     = contrast == allcontrasts(1);
    highcontrast    = contrast == allcontrasts(2);
    
    % variability of stimuli array
    targetstds      = data.targetarraystd(indsub);
    actualstds      = nanstd(perceptualvals,[],2);
    highstd         = actualstds > 0.0001;
    lowstd          = targetstds < 0.0001;
    lowsetsz        = setsize == 4;
    hisetsz         = setsize == 8;
    % cueing condition
    wastrialbiased  = data.biasedtrial(indsub) == 1;    
    
    respcor = data.wasrespcor(indsub);
    confrep = data.confidencerep(indsub);
    
    trialtypesn = [ ...
        (wastrialbiased==0) & lowcontrast  & lowstd  & lowsetsz ...
        (wastrialbiased==0) & lowcontrast  & highstd & lowsetsz ...
        (wastrialbiased==0) & highcontrast & lowstd  & lowsetsz ...
        (wastrialbiased==0) & highcontrast & highstd & lowsetsz ...
        (wastrialbiased==0) & lowcontrast  & lowstd  & hisetsz  ...
        (wastrialbiased==0) & lowcontrast  & highstd & hisetsz  ...
        (wastrialbiased==0) & highcontrast & lowstd  & hisetsz  ...
        (wastrialbiased==0) & highcontrast & highstd & hisetsz  ];
    
    trialtypesb = [ ...
        (wastrialbiased==1) & lowcontrast  & lowstd  & lowsetsz ...
        (wastrialbiased==1) & lowcontrast  & highstd & lowsetsz ...
        (wastrialbiased==1) & highcontrast & lowstd  & lowsetsz ...
        (wastrialbiased==1) & highcontrast & highstd & lowsetsz ...
        (wastrialbiased==1) & lowcontrast  & lowstd  & hisetsz  ...
        (wastrialbiased==1) & lowcontrast  & highstd & hisetsz  ...
        (wastrialbiased==1) & highcontrast & lowstd  & hisetsz  ...
        (wastrialbiased==1) & highcontrast & highstd & hisetsz  ];
    
    alltrialtypes = [trialtypesn trialtypesb];
    
    % get and store accuracies (and confidence) for each condition
    respcormat                  = repmat(respcor,[1 16]);
    respcormat(~alltrialtypes)  = nan;
    accuracies                  = nanmean(respcormat);
    allaccuracies(iSub,:)       = accuracies;
    confmat                     = repmat(confrep,[1 16]);
    confmat(~alltrialtypes)     = nan;
    confidences                 = nanmean(confmat);
    allconfidences(iSub,:)      = confidences;
    
    % get and store bias indices
    wascuecw        = data.whichcue(indsub)== 1;
    wascueccw       = data.whichcue(indsub)==-1;
    trialtypesbycue = [ ...
        (wastrialbiased==0) & lowcontrast   & lowstd   & wascuecw  & lowsetsz ...
        (wastrialbiased==0) & lowcontrast   & lowstd   & wascueccw & lowsetsz ...
        (wastrialbiased==0) & lowcontrast   & highstd  & wascuecw  & lowsetsz ...
        (wastrialbiased==0) & lowcontrast   & highstd  & wascueccw & lowsetsz ...
        (wastrialbiased==0) & highcontrast  & lowstd   & wascuecw  & lowsetsz ...
        (wastrialbiased==0) & highcontrast  & lowstd   & wascueccw & lowsetsz ...
        (wastrialbiased==0) & highcontrast  & highstd  & wascuecw  & lowsetsz ...
        (wastrialbiased==0) & highcontrast  & highstd  & wascueccw & lowsetsz ... 
        (wastrialbiased==0) & lowcontrast   & lowstd   & wascuecw  & hisetsz  ...
        (wastrialbiased==0) & lowcontrast   & lowstd   & wascueccw & hisetsz  ...
        (wastrialbiased==0) & lowcontrast   & highstd  & wascuecw  & hisetsz  ...
        (wastrialbiased==0) & lowcontrast   & highstd  & wascueccw & hisetsz  ...
        (wastrialbiased==0) & highcontrast  & lowstd   & wascuecw  & hisetsz  ...
        (wastrialbiased==0) & highcontrast  & lowstd   & wascueccw & hisetsz  ...
        (wastrialbiased==0) & highcontrast  & highstd  & wascuecw  & hisetsz  ...
        (wastrialbiased==0) & highcontrast  & highstd  & wascueccw & hisetsz  ...
        (wastrialbiased==1) & lowcontrast   & lowstd   & wascuecw  & lowsetsz ...
        (wastrialbiased==1) & lowcontrast   & lowstd   & wascueccw & lowsetsz ...
        (wastrialbiased==1) & lowcontrast   & highstd  & wascuecw  & lowsetsz ...
        (wastrialbiased==1) & lowcontrast   & highstd  & wascueccw & lowsetsz ...
        (wastrialbiased==1) & highcontrast  & lowstd   & wascuecw  & lowsetsz ...
        (wastrialbiased==1) & highcontrast  & lowstd   & wascueccw & lowsetsz ...
        (wastrialbiased==1) & highcontrast  & highstd  & wascuecw  & lowsetsz ...
        (wastrialbiased==1) & highcontrast  & highstd  & wascueccw & lowsetsz ... 
        (wastrialbiased==1) & lowcontrast   & lowstd   & wascuecw  & hisetsz  ...
        (wastrialbiased==1) & lowcontrast   & lowstd   & wascueccw & hisetsz  ...
        (wastrialbiased==1) & lowcontrast   & highstd  & wascuecw  & hisetsz  ...
        (wastrialbiased==1) & lowcontrast   & highstd  & wascueccw & hisetsz  ...
        (wastrialbiased==1) & highcontrast  & lowstd   & wascuecw  & hisetsz  ...
        (wastrialbiased==1) & highcontrast  & lowstd   & wascueccw & hisetsz  ...
        (wastrialbiased==1) & highcontrast  & highstd  & wascuecw  & hisetsz  ...
        (wastrialbiased==1) & highcontrast  & highstd  & wascueccw & hisetsz   ];
    
    num_conditions = 2*2*2*2*2;
    cwstimmat  = repmat( catofstim  ,[1 num_conditions]);
    ccwstimmat = repmat(~catofstim  ,[1 num_conditions]);
    corrmat    = repmat( respcor    ,[1 num_conditions]);
    wrongmat   = repmat( 1-respcor  ,[1 num_conditions]);
    
    % compute Signal Detection Theory measures
    signalpresent  = nansum( cwstimmat  .* trialtypesbycue) + 1  ;
    signalabsent   = nansum( ccwstimmat .* trialtypesbycue) + 1  ;
    numhits        = nansum( corrmat    .* trialtypesbycue .* cwstimmat ) + 0.5;
    numfa          = nansum( wrongmat   .* trialtypesbycue .* ccwstimmat) + 0.5;
    norminvhitr    = norminv( numhits./ signalpresent);
    norminvfar     = norminv( numfa  ./ signalabsent);
    criterion      = -0.5.*(norminvhitr+norminvfar);
    
    % measure the effect that the cue has on shifting the criterion:
    % biasindex (compute also for neutral trials using random cue values)
    biasindex      = (criterion(2:2:num_conditions)-criterion(1:2:(num_conditions-1)));
    allbiasindices(iSub,:) = biasindex;
end

end