function [allaccuracies, allconfidences, allbiasindices, alldiscaccs] = GetSummaryBehaviourMeasures_Exp4()

% load behavioural data exp 4
load('data_human_noise_blindness_Exp_4.mat')

allaccuracies   = nan(23,40);
allconfidences  = nan(23,40);
allbiasindices  = nan(23,40);
alldiscaccs     = nan(23,40);

% run analyses for the original task
for iSub = 1:23
    indsub   = data.subject == iSub;
    
    % define important variables
    perceptualvals  = data.pvs(indsub,:);
    meanofstim      = nanmean(perceptualvals,2);
    catofstim       = meanofstim>0;
    
    % contrast of stimuli
    contrast        = data.contrast(indsub);
    allcontrasts    = unique(contrast);
    lowcontrast     = contrast == allcontrasts(1);
    highcontrast    = contrast == allcontrasts(2);
    
    % variability of stimuli array
    targetstds      = data.targetarraystd(indsub);
    actualstds      = nanstd(perceptualvals,[],2);
    highstd         = actualstds > 0.0001;
    lowstd          = targetstds < 0.0001;

    % cueing condition
    wastrialbiased  = data.biasedtrial(indsub) == 1;    
    
    respcor = data.wasrespcor(indsub);
    confrep = data.confidencerep(indsub);

    asked_contrast      = data.disccontrast(indsub);
    asked_variability   = data.discvariability(indsub);
    disc_resp           = data.convardiscrep(indsub);
    disc_which_corr     = highcontrast.*asked_contrast + highstd.*asked_variability;
    disc_acc            = (disc_resp == 1) == disc_which_corr;
    correct_contrast    = disc_acc.*asked_contrast;
    correct_variability = disc_acc.*asked_variability;
    
    
    trialtypesn = [ ...
        (wastrialbiased==0) & lowcontrast  & lowstd ...
        (wastrialbiased==0) & lowcontrast  & highstd ...
        (wastrialbiased==0) & highcontrast & lowstd ...
        (wastrialbiased==0) & highcontrast & highstd ...
        (wastrialbiased==0) & lowcontrast  & lowstd  & correct_contrast ...
        (wastrialbiased==0) & lowcontrast  & highstd & correct_contrast ...
        (wastrialbiased==0) & highcontrast & lowstd  & correct_contrast ...
        (wastrialbiased==0) & highcontrast & highstd & correct_contrast ...
        (wastrialbiased==0) & lowcontrast  & lowstd  & correct_variability ...
        (wastrialbiased==0) & lowcontrast  & highstd & correct_variability ...
        (wastrialbiased==0) & highcontrast & lowstd  & correct_variability ...
        (wastrialbiased==0) & highcontrast & highstd & correct_variability ...
        (wastrialbiased==0) & lowcontrast  & lowstd  & ~correct_contrast ...
        (wastrialbiased==0) & lowcontrast  & highstd & ~correct_contrast ...
        (wastrialbiased==0) & highcontrast & lowstd  & ~correct_contrast ...
        (wastrialbiased==0) & highcontrast & highstd & ~correct_contrast ...
        (wastrialbiased==0) & lowcontrast  & lowstd  & ~correct_variability ...
        (wastrialbiased==0) & lowcontrast  & highstd & ~correct_variability ...
        (wastrialbiased==0) & highcontrast & lowstd  & ~correct_variability ...
        (wastrialbiased==0) & highcontrast & highstd & ~correct_variability];
    
    trialtypesb = [ ...
        (wastrialbiased==1) & lowcontrast  & lowstd ...
        (wastrialbiased==1) & lowcontrast  & highstd ...
        (wastrialbiased==1) & highcontrast & lowstd ...
        (wastrialbiased==1) & highcontrast & highstd ...
        (wastrialbiased==1) & lowcontrast  & lowstd  & correct_contrast ...
        (wastrialbiased==1) & lowcontrast  & highstd & correct_contrast ...
        (wastrialbiased==1) & highcontrast & lowstd  & correct_contrast ...
        (wastrialbiased==1) & highcontrast & highstd & correct_contrast ...
        (wastrialbiased==1) & lowcontrast  & lowstd  & correct_variability...
        (wastrialbiased==1) & lowcontrast  & highstd & correct_variability...
        (wastrialbiased==1) & highcontrast & lowstd  & correct_variability...
        (wastrialbiased==1) & highcontrast & highstd & correct_variability...
        (wastrialbiased==1) & lowcontrast  & lowstd  & ~correct_contrast ...
        (wastrialbiased==1) & lowcontrast  & highstd & ~correct_contrast ...
        (wastrialbiased==1) & highcontrast & lowstd  & ~correct_contrast ...
        (wastrialbiased==1) & highcontrast & highstd & ~correct_contrast ...
        (wastrialbiased==1) & lowcontrast  & lowstd  & ~correct_variability...
        (wastrialbiased==1) & lowcontrast  & highstd & ~correct_variability...
        (wastrialbiased==1) & highcontrast & lowstd  & ~correct_variability...
        (wastrialbiased==1) & highcontrast & highstd & ~correct_variability];
    
    alltrialtypes = [trialtypesn trialtypesb];
    
    % get and store accuracies (and confidence) for each condition
    respcormat                  = repmat(respcor,[1 40]);
    respcormat(~alltrialtypes)  = nan;
    accuracies                  = nanmean(respcormat);
    allaccuracies(iSub,:)       = accuracies;
    confmat                     = repmat(confrep,[1 40]);
    confmat(~alltrialtypes)     = nan;
    confidences                 = nanmean(confmat);
    allconfidences(iSub,:)      = confidences;
    discaccmat                  = repmat(disc_acc.*1,[1 40]);
    discaccmat(~alltrialtypes)  = nan;
    discaccs                    = nanmean(discaccmat);
    alldiscaccs(iSub,:)         = discaccs;
    
    % get and store bias indices
    wascuecw        = data.whichcue(indsub)== 1;
    wascueccw       = data.whichcue(indsub)==-1;
    trialtypesbycue = [ ...
        (wastrialbiased==0) & lowcontrast   & lowstd   & wascuecw   ...
        (wastrialbiased==0) & lowcontrast   & lowstd   & wascueccw  ...
        (wastrialbiased==0) & lowcontrast   & highstd  & wascuecw   ...
        (wastrialbiased==0) & lowcontrast   & highstd  & wascueccw  ...
        (wastrialbiased==0) & highcontrast  & lowstd   & wascuecw   ...
        (wastrialbiased==0) & highcontrast  & lowstd   & wascueccw  ...
        (wastrialbiased==0) & highcontrast  & highstd  & wascuecw   ...
        (wastrialbiased==0) & highcontrast  & highstd  & wascueccw  ... 
        (wastrialbiased==1) & lowcontrast   & lowstd   & wascuecw   ...
        (wastrialbiased==1) & lowcontrast   & lowstd   & wascueccw  ...
        (wastrialbiased==1) & lowcontrast   & highstd  & wascuecw   ...
        (wastrialbiased==1) & lowcontrast   & highstd  & wascueccw  ...
        (wastrialbiased==1) & highcontrast  & lowstd   & wascuecw   ...
        (wastrialbiased==1) & highcontrast  & lowstd   & wascueccw  ...
        (wastrialbiased==1) & highcontrast  & highstd  & wascuecw   ...
        (wastrialbiased==1) & highcontrast  & highstd  & wascueccw  ...
        (wastrialbiased==0) & lowcontrast   & lowstd   & wascuecw   & correct_contrast ...
        (wastrialbiased==0) & lowcontrast   & lowstd   & wascueccw  & correct_contrast ...
        (wastrialbiased==0) & lowcontrast   & highstd  & wascuecw   & correct_contrast ...
        (wastrialbiased==0) & lowcontrast   & highstd  & wascueccw  & correct_contrast ...
        (wastrialbiased==0) & highcontrast  & lowstd   & wascuecw   & correct_contrast ...
        (wastrialbiased==0) & highcontrast  & lowstd   & wascueccw  & correct_contrast ...
        (wastrialbiased==0) & highcontrast  & highstd  & wascuecw   & correct_contrast ...
        (wastrialbiased==0) & highcontrast  & highstd  & wascueccw  & correct_contrast ... 
        (wastrialbiased==1) & lowcontrast   & lowstd   & wascuecw   & correct_contrast ...
        (wastrialbiased==1) & lowcontrast   & lowstd   & wascueccw  & correct_contrast ...
        (wastrialbiased==1) & lowcontrast   & highstd  & wascuecw   & correct_contrast ...
        (wastrialbiased==1) & lowcontrast   & highstd  & wascueccw  & correct_contrast ...
        (wastrialbiased==1) & highcontrast  & lowstd   & wascuecw   & correct_contrast ...
        (wastrialbiased==1) & highcontrast  & lowstd   & wascueccw  & correct_contrast ...
        (wastrialbiased==1) & highcontrast  & highstd  & wascuecw   & correct_contrast ...
        (wastrialbiased==1) & highcontrast  & highstd  & wascueccw  & correct_contrast ...
        (wastrialbiased==0) & lowcontrast   & lowstd   & wascuecw   & correct_variability ...
        (wastrialbiased==0) & lowcontrast   & lowstd   & wascueccw  & correct_variability ...
        (wastrialbiased==0) & lowcontrast   & highstd  & wascuecw   & correct_variability ...
        (wastrialbiased==0) & lowcontrast   & highstd  & wascueccw  & correct_variability ...
        (wastrialbiased==0) & highcontrast  & lowstd   & wascuecw   & correct_variability ...
        (wastrialbiased==0) & highcontrast  & lowstd   & wascueccw  & correct_variability ...
        (wastrialbiased==0) & highcontrast  & highstd  & wascuecw   & correct_variability ...
        (wastrialbiased==0) & highcontrast  & highstd  & wascueccw  & correct_variability ... 
        (wastrialbiased==1) & lowcontrast   & lowstd   & wascuecw   & correct_variability ...
        (wastrialbiased==1) & lowcontrast   & lowstd   & wascueccw  & correct_variability ...
        (wastrialbiased==1) & lowcontrast   & highstd  & wascuecw   & correct_variability ...
        (wastrialbiased==1) & lowcontrast   & highstd  & wascueccw  & correct_variability ...
        (wastrialbiased==1) & highcontrast  & lowstd   & wascuecw   & correct_variability ...
        (wastrialbiased==1) & highcontrast  & lowstd   & wascueccw  & correct_variability ...
        (wastrialbiased==1) & highcontrast  & highstd  & wascuecw   & correct_variability ...
        (wastrialbiased==1) & highcontrast  & highstd  & wascueccw  & correct_variability ...
        (wastrialbiased==0) & lowcontrast   & lowstd   & wascuecw   & ~correct_contrast ...
        (wastrialbiased==0) & lowcontrast   & lowstd   & wascueccw  & ~correct_contrast ...
        (wastrialbiased==0) & lowcontrast   & highstd  & wascuecw   & ~correct_contrast ...
        (wastrialbiased==0) & lowcontrast   & highstd  & wascueccw  & ~correct_contrast ...
        (wastrialbiased==0) & highcontrast  & lowstd   & wascuecw   & ~correct_contrast ...
        (wastrialbiased==0) & highcontrast  & lowstd   & wascueccw  & ~correct_contrast ...
        (wastrialbiased==0) & highcontrast  & highstd  & wascuecw   & ~correct_contrast ...
        (wastrialbiased==0) & highcontrast  & highstd  & wascueccw  & ~correct_contrast ... 
        (wastrialbiased==1) & lowcontrast   & lowstd   & wascuecw   & ~correct_contrast ...
        (wastrialbiased==1) & lowcontrast   & lowstd   & wascueccw  & ~correct_contrast ...
        (wastrialbiased==1) & lowcontrast   & highstd  & wascuecw   & ~correct_contrast ...
        (wastrialbiased==1) & lowcontrast   & highstd  & wascueccw  & ~correct_contrast ...
        (wastrialbiased==1) & highcontrast  & lowstd   & wascuecw   & ~correct_contrast ...
        (wastrialbiased==1) & highcontrast  & lowstd   & wascueccw  & ~correct_contrast ...
        (wastrialbiased==1) & highcontrast  & highstd  & wascuecw   & ~correct_contrast ...
        (wastrialbiased==1) & highcontrast  & highstd  & wascueccw  & ~correct_contrast ...
        (wastrialbiased==0) & lowcontrast   & lowstd   & wascuecw   & ~correct_variability ...
        (wastrialbiased==0) & lowcontrast   & lowstd   & wascueccw  & ~correct_variability ...
        (wastrialbiased==0) & lowcontrast   & highstd  & wascuecw   & ~correct_variability ...
        (wastrialbiased==0) & lowcontrast   & highstd  & wascueccw  & ~correct_variability ...
        (wastrialbiased==0) & highcontrast  & lowstd   & wascuecw   & ~correct_variability ...
        (wastrialbiased==0) & highcontrast  & lowstd   & wascueccw  & ~correct_variability ...
        (wastrialbiased==0) & highcontrast  & highstd  & wascuecw   & ~correct_variability ...
        (wastrialbiased==0) & highcontrast  & highstd  & wascueccw  & ~correct_variability ... 
        (wastrialbiased==1) & lowcontrast   & lowstd   & wascuecw   & ~correct_variability ...
        (wastrialbiased==1) & lowcontrast   & lowstd   & wascueccw  & ~correct_variability ...
        (wastrialbiased==1) & lowcontrast   & highstd  & wascuecw   & ~correct_variability ...
        (wastrialbiased==1) & lowcontrast   & highstd  & wascueccw  & ~correct_variability ...
        (wastrialbiased==1) & highcontrast  & lowstd   & wascuecw   & ~correct_variability ...
        (wastrialbiased==1) & highcontrast  & lowstd   & wascueccw  & ~correct_variability ...
        (wastrialbiased==1) & highcontrast  & highstd  & wascuecw   & ~correct_variability ...
        (wastrialbiased==1) & highcontrast  & highstd  & wascueccw  & ~correct_variability ];
    
    num_conditions = 2*2*2*2*5;
    cwstimmat  = repmat( catofstim  ,[1 num_conditions]);
    ccwstimmat = repmat(~catofstim  ,[1 num_conditions]);
    corrmat    = repmat( respcor    ,[1 num_conditions]);
    wrongmat   = repmat( 1-respcor  ,[1 num_conditions]);
    
    % compute Signal Detection Theory measures
    signalpresent  = nansum( cwstimmat  .* trialtypesbycue) + 1  ;
    signalabsent   = nansum( ccwstimmat .* trialtypesbycue) + 1  ;
    numhits        = nansum( corrmat    .* trialtypesbycue .* cwstimmat ) + 0.5;
    numfa          = nansum( wrongmat   .* trialtypesbycue .* ccwstimmat) + 0.5;
    norminvhitr    = norminv( numhits./ signalpresent);
    norminvfar     = norminv( numfa  ./ signalabsent);
    criterion      = -0.5.*(norminvhitr+norminvfar);
    
    % measure the effect that the cue has on shifting the criterion:
    % biasindex (compute also for neutral trials using random cue values)
    biasindex      = (criterion(2:2:num_conditions)-criterion(1:2:(num_conditions-1)));
    allbiasindices(iSub,:) = biasindex;
end

end